server:
    port: 8080

spring:
    profiles: prod

    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url:  jdbc:postgresql://ec2-184-73-165-195.compute-1.amazonaws.com:5432/d3g86ff83k4tju?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        databaseName: d3g86ff83k4tju
        serverName: ec2-184-73-165-195.compute-1.amazonaws.com
        username: rdzctdmeyearey
        password: e1zL9gJP4bZxGiyO6CnoLwqhmp

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false



    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: ozay
