# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    mail:
        host: smtp.sendgrid.net
        port: 25
        username: OzayOrg
        password: Ozaysyn1124
        protocol: smtp
        tls: false
        auth: false
        from: ozay@ozay.us
    security:
        authentication:
            oauth:
                clientid: ozayapp
                secret: mySecretOAuthSecret
                # Token is valid 10 hours
                tokenValidityInSeconds: 36000
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: d0ad98419c3b64bf4581c98c98d03390ba5578cb
    swagger:
        title: ozay API
        description: ozay API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
