server:
    port: 8080

spring:
    profiles: dev

    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url:  jdbc:postgresql://localhost:5432/naofumiezaki
        databaseName: naofumiezaki
        serverName: localhost
        username: naofumiezaki
        password: adriarumia

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: ozay
